name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t saleor-core .
          docker tag saleor-core:latest 381285607374.dkr.ecr.us-east-1.amazonaws.com/saleor-core-update:latest

      - name: Push Docker image to ECR
        run: |
          docker push 381285607374.dkr.ecr.us-east-1.amazonaws.com/saleor-core-update

